name: Compile Sass to CSS

on:
  push:
    branches:
      - main  # Change this if your GitHub Pages branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Sass
        run: npm install -g sass

      - name: Compile SCSS
        run: sass styles/main.scss styles/main.css

      - name: Commit compiled CSS
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add styles/main.css
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-compile SCSS to CSS"
          git push
